import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable : "--font-poppins"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons : {
    icon : "/icon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} scroll-smooth antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
